apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-base  # Changed from "nginx" to avoid conflicts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-base  # Base selector (will be transformed)
  template:
    metadata:
      labels:
        app: nginx-base  # Must match selector
    spec:
      containers:
      - name: nginx
        image: nginx:1.21