resources:
- ../../base

namePrefix: dev-
nameSuffix: -kustomize

patches:
- path: replica-patch.yaml
  target:
    kind: Deployment
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: nginx-dev-kustomize
    env: dev
