apiVersion: v1
kind: Service
metadata:
  name: argocd-flask-app-service
spec:
  selector:
    app: argocd-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort  # Changed from LoadBalancer to work in minikube.